---
- name: configuration management
  hosts: all
  become: true

  tasks:
    - name: shut down ubuntu instances
      ansible.builtin.command: /sbin/shutdown -t now
      when:
        ansible_facts['os_family'] == "Debian"